name: eigenmodes-nanodisc-with-particle
dependencies:
  - python
  - future
  - ipython
  - jupyter
  - matplotlib>=1.5
  - numexpr
  - numpy
  - pandas>=0.18
  - statsmodels
  - pip:
     - brewer2mpl
